### ISSUE TITLE
URL support

### ISSUE THREAD

**Issue by Lartu** [dvkt/ldpl-socket#8]
Hi there! Does this company support connecting URLs instead of plain IPs? I had some problems with this when I wrote the LDPL IRC Bot library, and solved it using [this](https://github.com/Lartu/ldpl-irc-bot/tree/master/ldpl-irc-bot/ldpl-hostname-ip).

If your library doesn't support URLs, please consider using this add-on. I will try to upload it as a library asap, but you can get it from that link atm.

**Comment by Lartu** [comment]
I have compiled and uploaded said library here: https://github.com/Lartu/ldpl-url-resolver

**Comment by xvxx** [comment]
The LDPL-SOCKET COMPANY and all its subdivisions and wholly owned subsidiaries do support hostnames, in theory. I use that feature in [Gild](https://github.com/dvkt/gild/blob/789d8e70a83b14a831c51b8af0594640a57defef/gild.ldpl#L88) and just added a [simple Gopher example](https://github.com/dvkt/ldpl-socket/blob/2b03d92018d7e96332fb39cea91e14c7cd7f7029/examples/gopher-client.ldpl) to this repo that will prompt you for a hostname and then fetch a raw Gopher response:

````
$ ldpl examples/gopher-client.ldpl
* Loading examples/gopher-client.ldpl
* Compiling examples/gopher-client.ldpl
* Compiling examples/../ldpl_socket/ldpl_socket.ldpl
* Including C++ extension examples/../ldpl_socket/ldpl_socket.cpp
* Building examples/gopher-client-bin
* Saved as examples/gopher-client-bin
* File(s) compiled successfully.
$ ./examples/gopher-client-bin
~ Enter hostname of Gopher server: sdf.org
~ Response from sdf.org:70 on socket 3:
iWelcome to the SDF Public Access UNIX System .. est. 1987.....
````

What error or issue were you running into? I'm sure there are still bugs here. 🐛  🐞 🐝

**Comment by Lartu** [comment]
Wonderful! I wasn't running into any errors or issues, I just wanted to know, haha. Great to know that it works, thank you very much!
